### ISSUE TITLE
Update template to use lastest version of custom-card-helpers

### ISSUE THREAD

**Issue by royto** [custom-cards/boilerplate-card#25]
I use the template to create a custom cards.

I needed the state icon functionality so I updated the custom-card-helpers to 1.5.0.

Now the card is complaining about action Handling ... some exports are not here anymore.

Please update the template and provide new way of handling actions (hold, dbl tap, ...)

**Comment by royto** [comment]
`LovelaceCardEditor` is also missing from custom-card-helpers 😞

**Comment by peternijssen** [comment]
Same problem here :(

**Comment by elementzonline** [comment]
Same here, 
I managed to run it using 
```
npm install custom-card-helpers@1.3.9
```

**Comment by iantrich** [comment]
I'll try to get this sorted out this weekend. Been pretty busy

**Comment by iantrich** [comment]
should be fixed now
