### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by theOzzieRat** [custom-cards/boilerplate-card#28]
Firstly thanks for the effort in putting this boilerplate together.

But as a new developer to Lovelace/LitElement etc. Step 4 in the readme is very underwhelming.  Just telling people to update the bits labelled TODO in the code is fine, but in the code there is really no information on how to update each bit.  It would be great if there was more of an explanation and an example included in the code.

Unless I am missing something somewhere I can't find any clear documentation anywhere that describes the process of creating a custom card in any detail (where prior knowledge isn't assumed).

**Comment by iantrich** [comment]
This template is a starting point but by no means a catch-all for teaching Lovelace/LitElement/TypeScript. Those are all separate items. As for custom cards, the developer docs are a great resource: https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card
