### ISSUE TITLE
`paper-dropdown-menu` custom element doesnt work anymore with lazy loading

### ISSUE THREAD

**Issue by ljmerza** [custom-cards/boilerplate-card#33]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
As of HA 0.115, most custom elements are lazy loaded so using `paper-dropdown-menu` doesn't work anymore. 
**Last working release (if known):*0.114*

**Browser and Operating System:**
chrome/windows 10

**Description of problem:**
- make a new panel with only this boilerplate card
- open editor - dropdown will be broken
- if something internal to HA loads the `paper-dropdown-menu` element  (ie from state table) then this will work just fine since the js chuck will be loaded with the elements needed.

**Additional information:**
Need to find a way to trigger loading of custom elements from custom cards so we can use custom elements such as `paper-dropdown-menu` in custom cards again. Similar behavior for `ha-checkbox`, `ha-color-picker`, etc

**Comment by tomvanswam** [comment]
Workaround thanks to @thomasloven.
In `src/boilerplate-card.ts` add the following lines to`public static async getConfigElement(): Promise<LovelaceCardEditor>` (before the return)
```javascript
(await window.loadCardHelpers()).createCardElement({ type: 'entities', entities: [] });
await customElements.get('hui-entities-card').getConfigElement();
```

**Comment by ljmerza** [comment]
I would use the official importer coming in v0.116.

**Comment by iantrich** [comment]
Yeah I'll probably take a look this weekend to update unless someone beats me to it with a PR. 😉

**Comment by thomasloven** [comment]
The importer will load some elements, namely the ones that are used in more-info dialogs.

The `getConfigElement` thing will load elements that are used in card editors.
It's actually the best way we have found to get at them, and is the unofficially official method.

**Comment by ljmerza** [comment]
Which will also require your helpers as well? If so, I wouldn't want my cards relying on other cards.

**Comment by thomasloven** [comment]
No. It uses `window.loadCardHelpers()` which is shipped with lovelace.

**Comment by iantrich** [comment]
Yes there is the "custom" custom card helpers package and the core ones for loading/creating

**Comment by iantrich** [comment]
Fixed in https://github.com/custom-cards/boilerplate-card/releases/tag/1.2.0
