### ISSUE TITLE
Outdated Prettier version breaks on part of the card file and doesn't auto-format

### ISSUE THREAD

**Issue by dbuezas** [custom-cards/boilerplate-card#45]
package.json requires prettier@1.19.1, which throws on `import type xxxx from 'xxx'` statements (e.g [boilerplate-card.ts#L24](https://github.com/custom-cards/boilerplate-card/blob/master/src/boilerplate-card.ts#L24) )

Updating to latest (prettier@2.4.1) fixes it.

**Comment by iantrich** [comment]
Thanks, upgraded all dependencies in 1.4.1
