### ISSUE TITLE
UI Editor

### ISSUE THREAD

**Issue by iantrich** [custom-cards/boilerplate-card#5]
Provide a UI Editor that is bundled in the final release

**Comment by ljmerza** [comment]
added empty editor config. Never made an editor so not sure what's best practice on that so I left the ts file blank but the watcher/build works for both files

**Comment by iantrich** [comment]
I have a PR open here with an editor, just no working build https://github.com/custom-cards/boilerplate-card/pull/6

**Comment by ljmerza** [comment]
blah should have seen that my bad. I'll look at it
