### ISSUE TITLE
add info.md and hacs.json

### ISSUE THREAD

**Issue by iantrich** [custom-cards/boilerplate-card#8]
because @thomasloven is nitpicky 😜

**Comment by thomasloven** [comment]
Well, don't *you* think it's in the best interest of the community? 😜
@ludeeus

**Comment by iantrich** [comment]
Absolutely, it was introduced while I was kind of dormant and didn't really cross my mind 😄 was just being snarky

**Comment by ludeeus** [comment]
AFAIK `info.md` is **only** used for HACS.
[`hacs.json`](https://hacs.netlify.com/developer/general/#hacsjson) is far more important to implement.
There is also a key there to render README instead of info.md, in some cases, it does not make sense having both.
